CREATE TABLE SALES_ORDER_ITEM (
    SALES_ORDER_ID NVARCHAR(20) NOT NULL,
    ITEM_NO INTEGER NOT NULL,
    MATERIAL_ID NVARCHAR(20),
    MATERIAL_DESCRIPTION NVARCHAR(100),
    QUANTITY DECIMAL(15,3),
    UOM NVARCHAR(5),
    UNIT_PRICE DECIMAL(15,2),
    NET_VALUE DECIMAL(15,2),
    PLANT NVARCHAR(10)
);
